using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Domain;
using Domain.Acces;

namespace KIzuna
{
    public class KIzunaAI
    {
        public static void Decide()
        {
            Acces.DeciData.Tolerance = 5; //TODO: Nach Hinzufügen der Lernmethode entfernen
            DecideStage1();
        }

        #region Stage1
        private static void DecideStage1()
        {
            foreach (Data data in Acces.DataSet)
            {
                var groupOfAmmount = EvaluateGroupOfAmmountStage1(data.Menge);
                var groupOfValue = EvaluateGroupOfValueStage1(data.Wert*data.Menge);
                var same = CompareGoup(groupOfValue, groupOfAmmount);
                //TODO: Auslagern
                if (same)
                {
                    GroupedData dat = new GroupedData() { Data = data, Group = groupOfAmmount };
                    Acces.groupedData.Add(dat);
                }
                else
                {
                    DecideStage2(data, groupOfValue, groupOfAmmount);
                }
            }
            var a = Acces.groupedData;//TODO: Entfernen
        }

        private static int EvaluateGroupOfAmmountStage1(int amount)
        {
            int completeAmount = Acces.DataSet.Sum(a => a.Menge);
            double percent = 100 * (Convert.ToDouble(amount) / Convert.ToDouble(completeAmount));
            var i = 0;
            List<int> listamount = new List<int>();
            listamount = Acces.Setting.Amount;
            foreach (var data in listamount)
            {
                if (percent <= data)
                {
                    return i;
                }
                i++;
            }
            return i--;
        }

        private static int EvaluateGroupOfValueStage1(int value)
        {
            int completeValue = Acces.DataSet.Sum(a => a.Wert * a.Menge);
            double percent = 100 * (Convert.ToDouble(value) / Convert.ToDouble(completeValue));
            var i = 0;
            foreach (var data in Acces.Setting.Values)
            {
                if (percent >= data)
                {
                    return i;
                }
                i++;
            }
            return i--;
        }

        private static bool CompareGoup(int groupOfValue, int groupOfAmmount)
        {
            return groupOfAmmount == groupOfValue;
        }
        #endregion

        #region Stage2
        private static void DecideStage2(Data data, int groupValue, int groupAmount)
        {
            var groupDictance = groupAmount - groupValue;
            int? group = null;
            //TODO: auslagern
            if (groupDictance == 1 || groupDictance == -1)
            {
                LetKIzunaDecide(data, groupValue, groupAmount);            
            }
            else
            {
                if(groupDictance > 0)
                {
                    group = groupValue;
                    GroupedData dat = new GroupedData() { Data = data, Group = Convert.ToInt32(group)};
                    Acces.groupedData.Add(dat);
                }
                else
                {
                    //TODO: add Groupe Diffenrence bigger 1
                }
            }


        }

        private static void LetKIzunaDecide(Data data, int groupValueOld, int groupAmmountOld)
        {
            int groupAmmount = EvaluateGroupOfAmmountStage2(data.Menge);
            int groupValue = EvaluateGroupOfValueStage2(data.Wert);
            var same1 = CompareGoup(groupValue, groupAmmountOld);
            var same2 = CompareGoup(groupAmmount, groupValueOld );
            //TODO: Auslagern



            if(same1 == same2)
            {
                DecideStage3(data);
                var a = 2 + 2; //HINWEIS: Abfangen von fehlern
            }

            if (same1)
            {
                GroupedData dat = new GroupedData() { Data = data, Group = groupValue };
                Acces.groupedData.Add(dat);
            }
            else if (same2)
            {
                GroupedData dat = new GroupedData() { Data = data, Group = groupAmmount };
                Acces.groupedData.Add(dat);
            }

        }

        private static int EvaluateGroupOfValueStage2(int value)
        {
            int completeValue = Acces.DataSet.Sum(a => a.Wert * a.Menge);
            double percent = (100 * (Convert.ToDouble(value) / Convert.ToDouble(completeValue))) + Acces.DeciData.Tolerance;
            var i = 0;
            foreach (var data in Acces.Setting.Values)
            {
                if (percent >= data)
                {
                    return i;
                }
                i++;
            }
            return i--;
        }

        private static int EvaluateGroupOfAmmountStage2(int ammount)
        {
            int completeAmount = Acces.DataSet.Sum(a => a.Menge);
            double percent = 100 * ((Convert.ToDouble(ammount) / Convert.ToDouble(completeAmount))) + Acces.DeciData.Tolerance;
            var i = 0;
            List<int> listamount = new List<int>();
            listamount = Acces.Setting.Amount;
            foreach (var data in listamount)
            {
                if (percent <= data)
                {
                    return i;
                }
                i++;
            }
            return i--;
        }

        #endregion

        #region Stage3
        private static void DecideStage3(Data data)
        {
            //TODO: Erweitern (Prioritäten enfügen)
            throw new NotImplementedException();
        }
        #endregion

        #region Learn
        public void Learn()
        {

            //TODO: KIzuna das Lernen beibringen

        }
        #endregion
        /*
         .-.-.-.-.-.-.-.-.-.-.-.-.-.
        (   .   .   .   .   .   .   )
        (                           )
        ( .   .   .   .   .   .   . )
        (                           )
        (   .   .   .   .   .   .   )
        (                           )
        ( .   .   .   .   .   .   . )
        (                           )
         '-'-'-'-'-'-'-'-'-'-'-'-'-' 
         * 
         * 
         * 
         */
    }
}

/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxxdo:;,,,,,,,,,,,,'''''''''''''',,;:loxxxxxxxxxxxdl;'...............,lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kdoc;,,,,,,,,;:;,,,,''''''''''''''''''',;:loxxxxxxxxxdl;'...............,ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:;,'',,,,,,,:c;,,,,,,,,''''''''''''''......';cldxxxxxxxxoc,................;oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc,'.''''',,,,,cc;,,,,,,,,,,,',,''''''''''........',;coxxxxxxxdc,................'c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;'..'''''''''';ll;,,,,,,,,,,,,,,,'..''''''''''......''',:coxxxxxxo:,'.'''....''''''.,oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNk:....'''''''''';ll,',,,,,,,,,,,,,,,''''''''''''''''''''',,,;;:ldxxxxxoc;;,,,,,,,;:::::;,:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc,''''''''''',,,;oo;',,,,,,,,,,,,,,,,',:,'''''''''''''''',,,;:l:,,:oxxxxdollcc:::ccclodool::oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWMMMMMMMMMMMMMMMMMMWKo:;;,,,;;:;;;;,;;cdo::;,;;;;;::;,;,,,,,,:o:'','',,''',,,,,,,:cccodo:,':oxxxdollooooodolloxxxdood0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXO0KXXWMMMWWWMMMMMMMMMXkooooooodxkkddollodxkxkklldoccoxoccl:;;;;cxkc'',,,,;,,,,,,,,;;:looddddo;..:oxxxolloodddddoldxkkxdxxONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW00XXKXWMN0KXXWMMMMMWXkxkOkO00KKKKK0kdxOOkO0KKOodK0OO0OdxOxcldoxO0Oo'';;;:lc;:c::::cccodddddxxdl,.'cdxxdlloooddddoloxxxxdxkONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOKXXXKNXOKXKKWMMMWKkO00O0KKKKXXXK0kOK0OOKXXXkokXXXXX0xOXkcdKKKXKOo'';lodxxlcoxxxxoooodxddxxxxxo:..,lxxdllllllloollldooooxk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKXXXKK0OKXXKXWWXOkO00O0KKKXXXXX0k0K0OOKXXXKdo0XXXXX0k0XklkXXXX0Oo,';cxO00xllkOOOkxdddxkxdxxxxxdc'..:dxdlcc;,;;:ll:cc:;;:ox0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKXXXXKO0XXXXKX0ddkO0Ok0KKK0KKK0ddOkkO0KKKKkcdKXXXX0kk00ocOXK0K0Ol,clcdO00OocxO0OOOkxdxkkxdxxxxdoc,..;oddlc;'''',;:;;;''',:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKXXXXK0XXXXX0xlcdkOOxddO0kx000dcodxkxxk00x:cOXKKK0xdkxo:cOOdok0kl,dkllx0K0d:lxO0OOOkxdxxxdddxxddlc,..;lddl;'.....''.'....',lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKXXX0KXXXXXk:;:oxxol::clclkOx::loxdc:cdx:,o0KK0kdodxc''cdl:cxOOl;xKdcoOK0x::okOOOOkxooddoodddddlc:;..,codc'...............'oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKXXK0KXXXXKo,,;cl:;;;;;,,;co:';cxd:;;;:;..ckxdolldd:'.',;;;ckOOl;kXOlcd00x:,:dxdodddocccccloodol:::;..':ooc'...............'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXX00XXXXXO:',,,,,,,,,,'.','.';dd:,,,,'...;:::::od;...',,,;ok0O::0XKo:lxxl:',cl::::ccc:;;;:cllc:;,::,..':oo;................:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXK0KXXXXXx;',,,,',,,,,'.',..,od:,,,,'...',,;;;co:..'',,,,:xOKO;lKXXkc:cc::,';;;;;;;;;;,,;;::;;,,,,:c,..':oc'................oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKXKKXXXXXXd,,;;,,,,,,,,'','.'ldc,,,,,....;;,;;:l:',,',,,,cxOKXd;xXXN0c,;;:;;'';;;;,,,;,,,,,;;,,,,'',cc'..'cl;................,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXK0XNXXXXKo',;;;,,,,,;,',;'.cdl;;,;;'...,:;;;:c;'cc,;;;;cxOKNKc:0NXNKl'';;;::',,,,,,,,,,',,,,,,''''',lc'..;l:'................lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXKKXXXXXX0c,;:;;;;;;;;,',;';ol::;;;,'..,:c:;:l:,ll;::::cxOKXNO:dXNNNKl'',;,co;',,,,,,,,,,',,,'''''''':o:..':c,'''''''''.......;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKXXXXXXXO:,::::;;::::,,;;;loc::::;'..'cc:::c::do;::::cxOKNNXoc0NNNNXl'.';,lOl',,,,,'',,,'',,'''''''''ll'..;c;,''''''',,..'''''lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKKXNXXXXXKo,,::::;:::::,,;:loc:c:::,'..:lccc:,:xo;:c:loxOKNNNOcxNNNNNXl..';;oKx,',,,,'',,,''',,'''''''';dc...;;,'',,,,,.','''''';OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKXNXXXXXXk:,;:;:::cccc:,,:oolcccc:;'..:lcc:;;lxl;::cokk0XNNNXdoKNNNNNXo..';:kN0:';;;;,',,,,'',,,''''''''ld;...,,,'',,,,'..,,,''''dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXNNXXXXXXKdcoxl;:c:cccc;,;lollllcc:,.':lc::;:xkl;::cdk0KXNNNNkl0NNNNNNXl..,;lKNXd,,;;;,',;;;,',;,,''''''':dl'...,;'',;,,,...,;,','cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXNNNXXXXXX0xOKKklodxkkOOkkkkOkkkko;,'':lcc;:d0kc::cox0XNNNNNNOoONNNNNNNKc.',ckNNNO:,;:;,',;;;,,,;;,''''''',od:...';,',;;,,...';;,,';kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0KNNXXXXXXKK00XXXXXXNNNNNNNXXKKKKKk:'';llc::o0Kxc:cox0XNNNWNNXOokKKKK00OOx;.';oKXNNNd;:::;'';;:;,,;;;,'''''''cxl,...,,.',;;,....';;,,,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKKXNNXXKKKXXXXNNNNNXXXXXXXXXXKK00Oxl,';oxo:coOKOl:cok0XNNWNNNNKdodxxxxxxxxxl,.,cdxkkOKOc;c::,';:::;;:;,,,''',,,;dx:'..','.,;;'.....,;;,,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXNNNXKKXXNNNNNXXNXXXXK0Oxocloc;:c:;,:x0Ol:oOKOocldOKXNWWNWNXK0kOXNNNNNNWWWNx,'oKNNXK0KKd:ccc,',:::;;:;,,,,,,,,,,lko,..','.',;,.....';;;,:OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKXNNNNNNNNNNNNXXXXXKOxoc::;'',,'';::lkXNOook0kolxOKNNWWWWNNK0OO0XNNNWNNWNWWWKc'oKNNNNNNNN0l:cc;',:cc;,;:,,,,,,,,,;:xx:'.','.',;,.....',;;,;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNNNNNNNNNNNNXXXXKOxl,','',,'.,cc:okKNWNKOKNNXKXNNNWWWNNWWNNXXNWWNWWNWWWWWWNNkcxXWNNNNNNNNXo:ccc;,:cc;,::;,,,,,;;;;;okl,.''...';,.....',,;;;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNNNNNNNNNNXXXXKKK0Okkxxddoddllx000NWWWNNNWWWWWWNNWWWWWWNWWWWWWNNWWWWWWWWWWWWN0KNWNWNNNNNNNNx::clc';cc;,:::,,,;;;;;;;lkx;'''...',,.....',,,;:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWNNNNNNNNNXXXNNNNNNWWNNNNNNNNNXK0000KNWWWNWNWWWWWWWWWWWNWWWWWWWWWWWWWWNWWWWWWNNWWNNWWNNNNNNNO:;cdo',:c,';:c;,;;;;;;;;:xkc,'...''''.....',,,,;xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNWWWNNNNNNNNNNNNNWWWWNNXXXXXKKXXXXKKK00KKKKXXNNWWWWNWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWNNNNNNNNNNKl;ckx,';:'';:;,;;;;;;::::oko;'...''''.....',,,,,lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNNNWWWNNNNNNNNNNNNNNWN0xlxOdkOxddooodxxkkOO00KXNNNWNWWWWWWWWWWWWWWWWWWNNXKKKKKXXXNNNNNNNNNNNNNNNNx;oKO;.;:,';;,,:;;;::::::lxx:'....''......',,,,,;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oxXWNWNNNNNNNNNNNNNNNNNk,..lK0d;.......''''',;cd0XNNWNWWWWWWWWWWWWWWWWWWNXXXKK00KKKKKXXNNNNNNNNNNNNkckNKl.;c,';,,:::::::::::cdxc'.....'.......,,,,,:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.,OWWNNNNNNNNNNNNNNNNN0:...cOk:. .;cl,......';,;oKNNWWWWWWWWWWWWWWWWWWWWNNKOdl:::;;;::ccc::cclodkOKOdOXXd',:,,;,;:::::::::::coxo,'............',,,,:dxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXl...,kWNNNNNNNNNNNNNNNNN0l'...;Ok:.,kXNO;.......,'.,xXWNWWWWWWWWWWWWWWWWWWWNX0x:,'..........'.........,lOXXO;;:;:;;:::::::::::::lxd:'............',,,,:xxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;....'cx0XNNNNNNNNNNNNNNKo:,...,kXk;oXNNO:'...,.....;ONNNNNWWWWWWWWWWWWWWWWWNN0ooo,.... ....,c:';ol:;. .,lx00occcc;:;;:::::::::::cdxc,.............,,,,,dOxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNd........'cONNNNNNNNNWNNXdc:,....dXKdxXWWKo:;.','';,.oNWNNWWNNWWWWWWWNNNNNNNNNNKKW0;.'. .........:XWWN0c..'ck00xoc;;,;::::::::::::cdxl,.............',,,,oKkkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNKc.........'dXNNNWNNNNNXxc::;'...lKXKOXWMWOlolc:cll;:OWNNNNNNWWWWWWWWWNNNNNNNNNWWMKc,:;..,;;..;;.:XWWWWO;,dKXXXkc;;,;::::;;:::::::coxo;'............',,,,c00xKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWKc.........'c0NXKKXNNXkc::::,...:0XXXXXNWWX0kOOOkdoONNNNNNNNWWWWWWWWWNNNNNNNNNNWWWkcclc;;;;;cc;'dWMWMWklxKXXKxc;;,;::::,',:::::::coxdc,.............,,,,;ONkOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWXd'........';c:;,:oOkl::;;:;...;OXXXXKKXXNKOOOO0KXNNNNNNNWNNWWWWWWNNNNNNNNNNNNNNWNX0kkkkkkkxl;dXMMWWKk0XXXKd:;,,;:::;'':lc::::ccclxdc,........',...',,,,dNOxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWWWWWWN0o,.............'coc:::;::'..,xXXXXXXXXXXXXXXNNNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNKkkOOOOkddOXNNNXXXXXXXOl;,,;:::;,';okxl::::cc:cdd:'........';'..',,,,lXXx0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXNWWWWWWWWWKkc'...... ...,odc::::;;,...oKXXXXXXXXXXXXXNNNNNNNNNNNNNWNWWNNNNNNNNNNNNNNNNNNNNXKKKKK0KXXXKKXKXXXX0d;,,,:::,',:dOOOko:::c:cccdxc'........':,...,,,,:0WkkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXXXXNWWWWWWWWWWWXOdc,.    .;ddc::::;'....:OXXXXXXXXXXXXXNNNNNNNNNNNNNWWWNNWWNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXX0d:',,;;,,,;lkO00OOOd:::::::coxo,.........:;...',;,;kW0xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNXXXXNWWWWWWWWWWWWWWXOdc'..,ddc::::;'....,xXXKKKKXXXXXXXNNNNNNNNNNNWNNWWNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXKOo;'''',;:lxk0K000K0OOxc::::::cldd:.........::...',,,,oNXx0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWWNNXXXXNNWWNWWWWWWWWNNN0c'.,ddc::::;'.....c0XXXXXXXXXXXNNNNNNNNNNNNNXXWNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXK0xc,',;:loxOKKKKKK00KKOO0kl:::::cccoxl'........:c'...',;,:0WkkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNWWWWWNNNNNNNNNNNNNNNNK0KKo'..:ddl::::;'.....,xXXXXXXXXXXXNNNNNNNNNNNNNNNWWNNNNNNNNNNNNNNNNNNXXXXXXXXXXKXX0kdoodkO0KKXXXXKKKK00KK0OO0Oo:::::c::lxo,........;l,...',,,;xW0xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWWWWWWWWWWNNNNNXXXXKOolkXk,.'cdxdl::::;'......c0XXXXXXXXXNNNNNNNNNNNNNNWWWNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXKKXXXXXXXXXXXXKKKK000KKK00K0xc:::::::cdd:........,l:....,,,,lKKxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWWWWWWWWWWWWNNXXXXXXKko:ckNO;.'lxddxl:::;;'......'dXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXKK0000KKXXKK0xlc:::::::coxl'.......'cc....',,,;kXk0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWNNNXXXXXKOc,oKW0;.'lxocdxl:::;;'.......;kXNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXKKKK000000Okdl;'';::::::::lxo;........:o,....,,,,oKOOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWNNNNXXXXKxc:xNNk;.,oxo,,oxl:::;,.........:ONXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXNNNNNNXKK0kolcccc:;,''''',:::c::c:cdx:'.......;o:....',;,:OOkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWNNNNNNXXXKd:;xWXo'.:dxl'.'oxl:::;,..........:OXNNNNNNNNNNNNNNNXKKXXXNXXXXXKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKOo:;,,,,,,,,''''',;::cc:::coxc'.......,ll'...',;,;okkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWNNNNNNXXXKxclddO0c''cxd:...'lxl:::;,...........,dKNNNNNNNNNNNNNNNXXKXXXXKKKKKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0xc;;;;,,,,,,,'''''';:::::c:clxl'.......':o;....',,,cdkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWNNNNNXXXXkc:dXKdl:';oxo;.....lxl:::;,............':kXNNNNNNNNNNNNNNNXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0xc;;,,,,,,,,,,,'''''',::::::c:lxo,........,oc.....,,,;cdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWNNNNXXXXKxoxKWWO:;coxxl'......cxo:c:;,..............'ckXNNNNNNNNNNNNNNNNNXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOdc;;;;,,,,,,,,,,,'''''',;:::::c:cdd,........'ll'....',,,,lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNWWWWWWWWWWNNNNNXXXX0KNWWNOooxkxl;........lko:::;,................'ckKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xl:;;;;;,,,,,,,,,,,'''''''';:::::c:cdd;.........:o:.....',,':0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWNNNNNNNXXXXWMWWXOxxko:'........,k0ko:::;,..................':d0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKK00kc;;;;,,,,,,,,,,,,,'''''''.',:::::::cox:.........'ol'....',,,'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWWWWWWWWWNNNNNNNXXXXWMMWKOkxo:..........lKWXOdc::;,.....................,cx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKKK000000d:;;;;,,,,,,'',,,,'''''''...'::::::::oxc..........cd;.....',,',xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWWWWWWWWWNNNNNXXNNXXNMWN0Okl;,'........;kNMMXOdc::;,........................,lxKNNNNNNNNNNNNNNNNNNNNNNNNNNXXKK00000000000Oo;;;;,,,,,,,''',,,'''''''...';:::::::lxc..........;dc.....'',;,:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNWWWWWWWWWNNNNNNNXNXXXXNWNKOkdc'.''......'dXWMMMNOdc::;,..........................';lkKNNNNNNNNNNNNNNNXXXXKK00000000000000000Ol,;,,,,,,,,,''''''''''''.....,:::::::lxl..........'ld,.....';;,,c0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWNNNNNNNNNNXXXKNWX0Oko;'..',.....c0WMMMMMNkdl::;'.............................';okKXNNNNXXXKK0000000000000000000000000kc,;,,,,,,,,,,''''''''''......,:::::::cdl...........:dc.....';,,,,oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWNNNNNNNNNNXXXKXN0kOxc,.....,'..,xNMWMMMMMNkdo::;,................................';cd000000000000000000000000000000000kc,,,,,,,,,,,,'''''''''.......';::::::cdl'..........'ld,....';,';;;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWWWWWWWWWNNNNNNNNNXXXKXKdokxc'......,,'lKWMMMMMMMMWOddc:;,...................................:k00000000000000000000000000000000k:,,,,,,,,,,'''''''''''........;::::::cdo'...........:dc....';,';l:;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWNNNNNNNNNNXXXXKkllkkc'........:xNMMMMMMMMMMM0ddl::,...................................:k00000000000000000000000000000000x:,,,,,,,,,''''''..'''.........,::::c:cdo'...........'ld,...,,,,,co::0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWWWWWWWWWNNNNNNNNNNXXXXKOcckOo,........cdOWMMMMMMMMMMMKxxo::,'..................................:k00000000000000000000000000000000x:,,,,,,,''''''''..............';:::::cdl'............;dl...,'',,;dx;cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWNNNNNNNNNNXXXXXK0l;dOx;.......,xNKONMMMMMMMMMMMXxxoc:,'..................................:k00000000000000000000000000000000x:,,,,,,,''''''''...............;::c::ldl'.............lx:.''.',,,cOd;lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNWWWWWWWWWWNNNNNNNNNNXXXXXKKd;cOOc'......c0WMWXNMMMMMMMMMMMNxooc:;'..................................:k00000000000000000000000000000000kollllccc:;''''''...............;:::::ldl..............,dd;'...,,,,dKd;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWNNNNNNNNNXXXXXXKKx;;x0d;'....,dXMMMMMMMMMMMMMMMMMMk:ol:;'..................................:k00000000000000000000000000000000Okxxxxxxxxd:''''''..............,:::::ldc...............:dc'...',,,:OXo;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWNNNNNNNNXNXXXXXKX0c,ckkc'....;OWMMMMMMMMMMMMMMMMMMWx,coc:,................................;cdO0000000000000000000000000000000Okxxkkkkkkkkxc,'''...............,:ccc:od:................:l:....,,,,lXXl;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWWWWWWWWWWWWNNNNNNNNNXXXXXXKXXd;,ckx:'...;0WMMMMMMMMMMMMMMMMMMMXc.;ll:;..............................;okkk000000000000000000000000000000OOkkOOOOkkkkkkkxl,''...............':c::cod;................,od;...',,,;xNKl:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWWNNNNNNNNNXXXXXXKKNKl,,:xk:'..;0WMMMMMMMMMMMMMMMMMMMM0,.'coc:,..........................':dkOOkO000000000000000000000000000OOOkOOOOOOOOOkkkkkkxl,''..............'::::cdo;...............,,:xo'..',,,,c0W0c:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWWWNNNNNNNNXXXXXXKdkNO:,,;dkc'.;OWMMMMMMMMMMMMMMMMMMMMWx...,lo:;'.......',;;::cclooodddoodxOOkkkO0000000000000000000000000OOOOOOOOOOOOOOOOOOOOkkkko,...............'::c:cdl,..............',..cxl...',,,,oXWO:c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWWWWWWWWWWWWNNNNNNNNNNXXXXXKx:dXd,,,;okl',kWWMMMMMMMMMMMMMMMMMMMMNo....:dc:,...,coxkkk0KKXNNNNNNNX0OOkkkkO000000000000000000000000OOkOOO000000000000000OOOOOOkdc,.............':c::ldc'.......'.....',...'ox;..',,,,;xNWk;lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWWWNNNNNNNNNNXXXXXKKk;o0o,;;;lko'lXMMMMMMMMMMMMMMMMMMMMMMK:.....coc;''oKXNXXXXNNNNNNNNNXK0OkkkkO00000000000000000000000OOOOO000000000000000000000000000Oxl;'..........':c:coo;.......''....',.....;xo,..',,,,:OWNx;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWWWNNNNNNNNNXXXXXXKKNKcckc,;;,ckd;xWMMMMMMMMMMMMMMMMMMMMMMO'...'cdxo:;'lXWNNNNNNNNNNNNXXK0kkkO00000000000000000000000OkO0KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXK00Okdl:;,'.....':c:cdl'.......'....',.......cxc...,,,,,lKMXo;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWWWWNNNNNNNNXXXXXXXXKNMNd:l:,;;;:xxo0MMMMMMMMMMMMMMMMMMMMMMWx,;lxKNN0Odc,,xNNNNNNNNNNNNNXKOkkO00000000000KKK00K00000OOO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNXK00OOO000KKK0Okxol;;:::ldc............,,........'ox;..',,,,,dNMKl:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWWWNNNNNNNNNNXXXXXXKKNMMW0c;;,;;;;lkOXMMMMMMMMMMMMMMMMWWWNNNNK0XNWNNNXKKkc,;ONNNNNNNNNNNNXK0KKXKKKKKKKKKK000000000OOOOKXNNNNNNNNNNNNNNNNNNNNNNNNNNXK0OkkkO0KXXXKK0000000KKxc:coo,...........,,..........;xo'..',,,,:OWWO:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWWNNWWWWWWWWWWWWWNNNNNNNNNXXXXXXXKKNMMMMWk:,',;;;:okKWMMMMMMMMMWWWNNNNNNNNNNNNNNNNNNNNXXkc,lKNNNNNNNNNXXXXNNNNNXXKKKK0KKKKKKKXXKKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNXX0Okkk0KXXXXKK0OOOOkkkxddxoc:lo:...........,'............cx:..',,,,'lXMNx:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWWWWNNNNNNNNNXXXXXXXKKNWMMMMMW0c,,,;;;cdOXWMMWXKKXXNNNNNNNNNNNNNNNNNNNNNNNNXXOl;xNNNNNNNXXXXXXXNNNNNNXXXKXXNXXXXXKXXXNNNNNNNNNNNNNNNNNNNNNNNNNNXK0Okkk0KXXXXKKKKKXXXXKKK00kxoc:cloo:........................'od,..',,,',xWMXo:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNNWWWWWWWWWWWWWNNNNNNNNNXXXXXXXXKKNMMMMMMMMWKo;,,;;:lxOOdc:;,':kNNNNNNNNNNNNNNNNNNNNNNNXXNNKdckNNNNXXXXXXXXNNNNNNNNNNNXXXXXKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkkk0KXXXXKKKKXNNNNNNNNNNXXXKkl:lodO0l........................;xl..',,,,'cKMW0:lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWNNNWWWWWWWWWWWWWNNNNNNNNNNXXXXXXXKKNWMMMMMMMMWW0l;;,,;:okx:. ...';:lok0XNNNNNNNNNNNNXXXXXNNNNNXkd0NNXXXXXXNNNNNNNNNNNNNXXNXKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kkkOKXXXXK00KXNNNNNNNNNNNNNNNNXd::loxOK0l........................lx;..,,,,,,dNMNd;xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWNNWWWWWWWWWWWWWWWNNNNNNNNXXXXXXXXKKNMMMMWWWNNNNNNKo:;,,,cdxxl.  .......,dKNNNNNNNNXXXXXXNNNNNNNNNK0XNXXXXXXXXXXXXXNNNNNNNNXKKXNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkkO0KXXXK00KXNNNNNNNNNNNNNNNNNNNOl::oOkk0XO:.......................,xo'.',,,,':OWMKc:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWNNWWWWWWWWWWWWWWWNNNNNNNNXXXXXXXXKKXWMWWNNNNNNWWWWN0l;;,'':oxko'     .''.,kXNNNNXXXXXXXXNNNNNNNNNNNNNNXXXXXXXXXXXXXKKKKXXNXKXNNNNNNNNNNNNNNNNNNNNNNNNNNNKOxxk0XXXXX0kOXNNNNNNNNNNNNNNNNNNNNXx::cxXX0OKXx'.......................lx;.',,,,,,dNMNd,xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/